//USER Login and Register Actions Types
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

// User Data
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

//Update Data

//Water Cups
export const USER_UP_DRINKS = "USER_UP_DRINKS";
export const USER_DOWN_DRINKS = "USER_DOWN_DRINKS";
export const LOAD_DRINKS_DATA = "LOAD_DRINKS_DATA";
export const USER_ERROR_DRINKS = "USER_ERROR_DRINKS";

//Meals
export const USER_MEAL_PLUS = "USER_MEAL_PLUS";
export const USER_MEAL_MINUS = "USER_MEAL_MINUS";

//Medicine
export const USER_MEDICINE_ADD = "USER_MEDICINE_ADD";
export const USER_MEDICINE_REMOVE = "USER_MEDICINE_REMOVE";

//steps
export const STEPS_ACTION_UPDATE = "STEPS_ACTION_UPDATE";

//sleeps
export const SLEEPS_ACTION_UPDATE = "SLEEPS_ACTION_UPDATE";

//weight
export const USER_UPDATE_WEIGHT = "USER_UPDATE_WEIGHT";
